#!/usr/bin/env python3
#Lifted from https://en.wikipedia.org/wiki/List_of_British_bingo_nicknames 
calls = { 
'1' :	"Kelly's eye",
'2' :	"One little duck",
'3' :	"Cup of tea",
'4' :	"Knock at the door",
'5' :	"Man alive",
'6' :	"Half a dozen",
'7' :	"Lucky",
'8' :	"Garden gate",
'9' :	"Doctor's orders",
'10' :	"Liz's den",
'11' :	"Legs eleven",
'12' :	"One dozen",
'13' :	"Unlucky for some",
'14' :	"Valentine's Day",
'15' :  "Young and keen",
'16' :	"Never been kissed",
'17' :	"Dancing Queen",
'18' :	"Coming of age",
'19' :	"Goodbye teens",
'20' :	"One score",
'21' :	"Key of the door",
'22' :	"Two little ducks",
'23' :	"The Lord is My Shepherd",
'24' :	"Double dozen",
'25' :	"Duck and dive",
'26' :	"Two and six, half a crown",
'27' :	"Duck and a crutch",
'28' :	"In a state",
'29' :	"Rise and shine",
'30' :	"Dirty Gertie",
'31' :	"Get up and run",
'32' :	"Buckle my shoe",
'33' :	"All the threes",
'34' :	"Ask for more",
'35' :	"Jump and jive",
'36' :	"Triple dozen",
'37' :  "More than 11", 
'38' :	"Christmas cake",
'39' :	"Steps",
'40' :	"Life begins",
'41' :  "Time for fun",
'42' :  "Winne the Pooh",
'43' :	"Down on your knees",
'44' :	"Droopy drawers",
'45' :	"Halfway there",
'46' :	"Up to tricks",
'47' :  "Four and seven",
'48' :	"Four dozen",
'49' :  "PC",
'50' :	"It's a bullseye!",
'51' :  "Tweak of the thumb",
'52' :	"Danny La Rue",
'53' :	"Here comes Herbie",
'54' :	"Man at the door",
'55' :	"All the fives",
'56' :	"Shotts Bus",
'57' :	"Heinz varieties",
'58' :  "Make them wait",
'59' :	"The Brighton Line",
'60' :	"Five dozen",
'61' :  "Baker's bun",
'62' :	"Tickety-boo",
'63' :  "Tickle me",
'64' :	"Almost retired",
'65' :	"Retirement age, Stop work",
'66' :	"Clickety click",
'67' :	"Stairway to Heaven",
'68' :	"Pick a Mate",
'69' :	"Anyway up",
'70' :  "Three score and ten",
'71' :	"Bang on the drum",
'72' :	"Six dozen",
'73' :	"Queen Bee",
'74' :	"Hit the floor",
'75' :  "Strive and strive",
'76' :	"Trombones",
'77' :	"Two little crutches",
'78' :	"39 more steps",
'79' :  "One more time",
'80' :	"Eight and blank",
'81' :	"Stop and run",
'82' :	"Straight on through",
'83' :	"Time for tea",
'84' :	"Seven dozen",
'85' :	"Staying alive",
'86' :	"Between the sticks",
'87' :	"Torquay in Devon",
'88' :	"Two fat ladies",
'89' :	"Nearly there",
'90' :	"Top of the shop",
}

